# Generated by Django 5.2.11 on 2026-04-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_analysis_dna_sample_alter_modellog_dna_sample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedface',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='generated_faces/'),
        ),
        migrations.AlterModelTable(
            name='generatedface',
            table='generated_face',
        ),
    ]
