# Generated by Django 5.2.11 on 2026-04-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_generatedface_image_alter_generatedface_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedface',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
