# Generated by Django 5.2.11 on 2026-04-15 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0007_alter_generatedface_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnasample',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modellog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prediction',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='prediction',
            name='idx_prediction_user',
        ),
        migrations.RemoveIndex(
            model_name='prediction',
            name='idx_prediction_dna_sample',
        ),
        migrations.RemoveIndex(
            model_name='prediction',
            name='idx_prediction_created_at_desc',
        ),
        migrations.RenameIndex(
            model_name='dnasample',
            new_name='dna_sample_user_id_e9cdf6_idx',
            old_name='idx_dnasample_user',
        ),
        migrations.RenameIndex(
            model_name='dnasample',
            new_name='dna_sample_uploade_98852d_idx',
            old_name='idx_dnasample_uploaded_at',
        ),
        migrations.RenameIndex(
            model_name='modellog',
            new_name='model_logs_dna_sam_ab37dc_idx',
            old_name='idx_modellog_dna_sample',
        ),
        migrations.RenameIndex(
            model_name='modellog',
            new_name='model_logs_status_023134_idx',
            old_name='idx_modellog_status',
        ),
        migrations.RenameIndex(
            model_name='modellog',
            new_name='model_logs_created_19715a_idx',
            old_name='idx_modellog_created_at_desc',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='dna_sample',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='user',
        ),
        migrations.AddField(
            model_name='analysis',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedface',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedface',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prediction',
            name='analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='core.analysis'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='dna_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='core.dnasample'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dnasample',
            name='sequence_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='modellog',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='modellog',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterModelTable(
            name='analysis',
            table='analysis',
        ),
    ]
