# Generated by Django 5.2.11 on 2026-04-16 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_prediction_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='dna_sample',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis', to='core.dnasample'),
        ),
    ]
