# Generated by Django 5.2.11 on 2026-04-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_analysis_dna_sample'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dnasample',
            name='dna_sample_user_id_e9cdf6_idx',
        ),
        migrations.RemoveIndex(
            model_name='dnasample',
            name='dna_sample_uploade_98852d_idx',
        ),
        migrations.AddField(
            model_name='dnasample',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnasample',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='analysis',
            table=None,
        ),
        migrations.AlterModelTable(
            name='dnasample',
            table=None,
        ),
        migrations.AlterModelTable(
            name='generatedface',
            table=None,
        ),
        migrations.AlterModelTable(
            name='prediction',
            table=None,
        ),
    ]
