# Generated by Django 5.2.11 on 2026-05-10 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_prediction_gender_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedface',
            name='analysis',
        ),
        migrations.AddField(
            model_name='generatedface',
            name='prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_faces', to='core.prediction'),
        ),
        migrations.AlterModelTable(
            name='generatedface',
            table='generated_face',
        ),
    ]
