# Generated by Django 5.2.11 on 2026-05-10 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_generatedface_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedface',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_faces_old', to='core.analysis'),
        ),
    ]
