# Generated by Django 5.2.11 on 2026-05-10 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_generatedface_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedface',
            name='analysis',
        ),
        migrations.AlterField(
            model_name='generatedface',
            name='prediction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_faces', to='core.prediction'),
        ),
    ]
